#!/usr/bin/env python
import argparse, json, pickle, os, re, subprocess, glob

from DevTools.Utilities.utilities import python_mkdir

__gitversion__ = subprocess.check_output(["git", "describe", "--always"]).strip()

j=0

def getTriggers(baseDir):
    allFiles = glob.glob('{0}/png/*.png'.format(baseDir))
    ptFiles = glob.glob('{0}/png/*_pt.png'.format(baseDir))
    etaFiles = glob.glob('{0}/png/*_eta.png'.format(baseDir))
    names = []
    for f in sorted(allFiles):
        if f in ptFiles: continue
        if f in etaFiles: continue
        names += [os.path.basename(os.path.splitext(f)[0])]
    return names

def parseDirectory(obj, outputDirectory) :
    '''
        Generates HTML files in outputDirectory
    '''

    python_mkdir(outputDirectory)
    with open(os.path.join(outputDirectory, 'index.html'), 'w') as index :
        index.write(HTML.header.format(
            object=obj,
        ))

        for trigName in getTriggers(outputDirectory) :
            parseTrigger(obj, trigName, index)
        
        index.write(HTML.footer.format(
                version=__gitversion__
            ))

def parseTrigger(obj, triggerName, index) :
    index.write(HTML.effDirItem.format(
        triggerName=triggerName,
    ))


# HTML Templates
class HTML :
    header = '''<html>
<head>
    <title>Efficiency summary for {object} triggers</title>
    <style type="text/css">
        div.effResult {{
            margin: auto;
            width: 80%;
            border: 2px solid #888888;
        }}

        table {{
            width: 100%;
        }}
    </style>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<h2>Efficiency summary for {object} triggers</h2>
'''

    effDirItem = '''<div class="effResult">
    <h3>Efficiency results for {triggerName}</h3><br />
    <div style="text-align: center;"><b>Summary Plot</b><br /><img src="png/{triggerName}.png" /><br /><img src="png/{triggerName}_pt.png" /><img src="png/{triggerName}_eta.png" /></div>
</div>
<br/>'''

    footer = '''
Generated using DevTools/TagAndProbe version {version}<br />
</body>
</html>
'''

def main() :
    parser = argparse.ArgumentParser(description='Dumps fit info generated by TagAndProbe old fitter into HTML summary')
    parser.add_argument('object', choices=['electron','muon'], help='Directory name in root files to load')
    parser.add_argument('--output', '-o', help='Directory name for output', required=True)
    args = parser.parse_args()
    
    python_mkdir(args.output)

    parseDirectory(args.object, args.output)

if __name__ == '__main__' :
    main()

